name: lightning

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python>=3.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.6
  - pytorch-lightning
  - numpy
  - matplotlib
  - seaborn
  - ipython
  - tensorboard
